<a href="https://colab.research.google.com/github/avnisinngh/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing pytorch
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
# check if gpu is available or not
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Ussing GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avilable. Using CPU")

GPU not avilable. Using CPU


## Creating a Tensor

In [ ]:
# using empty => it allocates memory and does not assign value to it , but rather use the value that is already present in that space
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros => all values will initialize with zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2343, 0.1026, 0.7794],
        [0.3592, 0.9858, 0.4895]])

In [ ]:
# use of seed => everytime rand is used it produces a diff vales , but whatis you want to uhave same values each time
torch.rand(2,3)

tensor([[0.1952, 0.0897, 0.7438],
        [0.8196, 0.1763, 0.8528]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor => create custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->" , torch.arange(0,10))

#using linspace
print("using linespace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linespace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [3]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
x.shape

torch.Size([2, 3])

In [5]:
torch.empty_like(x)

tensor([[  17179869284, 6090263627143,  197568495620],
        [            0,             0,             0]])

In [6]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [7]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [13]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6282, 0.5570, 0.4502],
        [0.5354, 0.2600, 0.2223]])

## Tensor Data Types

In [9]:
# find data type
x.dtype

torch.int64

In [10]:
# asign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [12]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

## 1. Scaler

In [14]:
x = torch.rand(2,2)
x

tensor([[0.0550, 0.2245],
        [0.9769, 0.4673]])

In [25]:
# addition
x +2

# subtraction
x-1

# multiplication
x*3

# division
x /3
# int division
(x*100) / 10
# mod
(x*100) % 10
# power
x**8

tensor([[8.4207e-11, 6.4586e-06],
        [8.2936e-01, 2.2754e-03]])

## 2. Element Wise Operation

In [26]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3736, 0.1933, 0.4487],
        [0.0559, 0.7824, 0.5171]])
tensor([[0.8226, 0.6252, 0.9772],
        [0.3597, 0.4782, 0.4405]])


In [32]:
# add
a+b
# sub
a-b
# mupltiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.3736, 0.1933, 0.4487],
        [0.0559, 0.3042, 0.0766]])

In [34]:
c = torch.tensor([1,-2,3,-4])

In [35]:
# abs = absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
# negetive
torch.neg(c)

tensor([-1,  2, -3,  4])

In [37]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [38]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [39]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [40]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [42]:
# clamp => you can put numbers in a specific range
torch.clamp(d, min=2, max =3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation