<a href="https://colab.research.google.com/github/avnisinngh/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing pytorch
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
# check if gpu is available or not
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Ussing GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avilable. Using CPU")

GPU not avilable. Using CPU


## Creating a Tensor

In [ ]:
# using empty => it allocates memory and does not assign value to it , but rather use the value that is already present in that space
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros => all values will initialize with zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2343, 0.1026, 0.7794],
        [0.3592, 0.9858, 0.4895]])

In [ ]:
# use of seed => everytime rand is used it produces a diff vales , but whatis you want to uhave same values each time
torch.rand(2,3)

tensor([[0.1952, 0.0897, 0.7438],
        [0.8196, 0.1763, 0.8528]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor => create custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->" , torch.arange(0,10))

#using linspace
print("using linespace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linespace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[  17179869284, 6090263627143,  197568495620],
        [            0,             0,             0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6282, 0.5570, 0.4502],
        [0.5354, 0.2600, 0.2223]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# asign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

## 1. Scaler

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.0550, 0.2245],
        [0.9769, 0.4673]])

In [ ]:
# addition
x +2

# subtraction
x-1

# multiplication
x*3

# division
x /3
# int division
(x*100) / 10
# mod
(x*100) % 10
# power
x**8

tensor([[8.4207e-11, 6.4586e-06],
        [8.2936e-01, 2.2754e-03]])

## 2. Element Wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3736, 0.1933, 0.4487],
        [0.0559, 0.7824, 0.5171]])
tensor([[0.8226, 0.6252, 0.9772],
        [0.3597, 0.4782, 0.4405]])


In [ ]:
# add
a+b
# sub
a-b
# mupltiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.3736, 0.1933, 0.4487],
        [0.0559, 0.3042, 0.0766]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs = absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negetive
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp => you can put numbers in a specific range
torch.clamp(d, min=2, max =3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high =10, dtype=torch.float32)
e

tensor([[4., 4., 0.],
        [1., 3., 9.]])

In [ ]:
# sum
torch.sum(e)

#  sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([10, 16])

In [ ]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [ ]:
# median
torch.median(e)

tensor(3.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1464)

In [ ]:
# variance
torch.var(e)

tensor(9.9000)

In [ ]:
# argmax => position of highest element
torch.argmax(e)


tensor(5)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

## 4. Matrix Operation

In [ ]:
f = torch.randint(size=(2,3), low = 0, high = 10)
g = torch.randint(size=(3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[3, 9, 1],
        [8, 6, 8]])
tensor([[2, 0],
        [3, 1],
        [0, 3]])


In [ ]:
# Matrix multiplication
torch.matmul(f,g)

tensor([[33, 12],
        [34, 30]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

print(vector1)
print(vector2)

tensor([1, 2])
tensor([3, 4])


In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 8],
        [9, 6],
        [1, 8]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 9., 4.],
        [5., 6., 4.],
        [7., 2., 6.]])

In [ ]:
# determinant
torch.det(h)

tensor(-62.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.4516,  0.7419, -0.1935],
        [ 0.0323,  0.1613, -0.1290],
        [ 0.5161, -0.9194,  0.4355]])

## 5. Comparison Operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 8, 3],
        [7, 4, 2]])
tensor([[3, 4, 3],
        [7, 4, 4]])


In [ ]:
# greater than
i > j

# less than
i<j

# equal to
i == j


# not equal to
i != j

# greater than equal to
i >= j

# less than equal to
i <= j

tensor([[ True, False,  True],
        [ True,  True,  True]])

## 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 0., 7.],
        [5., 1., 8.]])

In [ ]:
# log
torch.log(k)

tensor([[2.1972, 0.6931, 2.0794],
        [2.0794,   -inf, 0.6931]])

In [ ]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 7.3891e+00, 2.9810e+03],
        [2.9810e+03, 1.0000e+00, 7.3891e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 1.4142, 2.8284],
        [2.8284, 0.0000, 1.4142]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.8808, 0.9997],
        [0.9997, 0.5000, 0.8808]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0067, 0.2689, 0.2689],
        [0.9933, 0.7311, 0.7311]])

In [ ]:
# relu
torch.relu(k)

tensor([[0., 0., 7.],
        [5., 1., 8.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0965, 0.4073, 0.2495],
        [0.3514, 0.9873, 0.1249]])
tensor([[0.4707, 0.1508, 0.7513],
        [0.2183, 0.1189, 0.2056]])


In [ ]:
m + n # it will store the reuslt in a new tensor in the memeory , so it will take so place in the memory and it can cause problem

tensor([[0.5671, 0.5581, 1.0008],
        [0.5697, 1.1062, 0.3305]])

In [ ]:
torch.relu(m)

tensor([[0.0965, 0.4073, 0.2495],
        [0.3514, 0.9873, 0.1249]])

In [ ]:
m.relu_() # underscore represent inplace opreations

tensor([[0.0965, 0.4073, 0.2495],
        [0.3514, 0.9873, 0.1249]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.8956, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
b = a # b is a copy of a

In [ ]:
b

tensor([[0.8956, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
b

tensor([[0.0000, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
id(a)

134103055650880

In [ ]:
id(b)

134103055650880

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
b

tensor([[0.0000, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.8616,  0.7010],
        [ 0.3170,  0.4739,  0.2747]])

In [ ]:
b

tensor([[0.0000, 0.8616, 0.7010],
        [0.3170, 0.4739, 0.2747]])

In [ ]:
id(a)

134103055650880

In [ ]:
id(b)

134103055796816

## Tensor Operations on GPU

In [2]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')
device

device(type='cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.0729, 0.7519, 0.0047],
        [0.0447, 0.0530, 0.6436]], device='cuda:0')

In [7]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.0201, 0.1742, 0.1056],
        [0.2113, 0.4593, 0.7928]])

In [8]:
a.to(device)

tensor([[0.0201, 0.1742, 0.1056],
        [0.2113, 0.4593, 0.7928]], device='cuda:0')

In [9]:
b = a.to(device)

In [10]:
b + 5

tensor([[5.0201, 5.1742, 5.1056],
        [5.2113, 5.4593, 5.7928]], device='cuda:0')

In [14]:
import time

# define the size of matrices
size = 1000 # large size for performance comparison

# creating random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# measure time on GPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Msatrix multiplication on CPU
end_time = time.time()
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# measure time on GPU
start_time = time.time()
result_gpu= torch.matmul(matrix_gpu1, matrix_gpu2) # Msatrix multiplication on GPU
torch.cuda.synchronize() # ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds")

# Complete result
print("\n Speedup (CPU / GPU time): ", cpu_time/gpu_time)

Time on CPU:  0.0162 seconds
Time on GPU:  0.0010 seconds

 Speedup (CPU / GPU time):  16.55550134179068


## Reshaping Tensors

In [16]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [18]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
b = torch.rand(2,3,4)
b

tensor([[[6.9767e-02, 3.1439e-01, 1.2981e-01, 4.3528e-01],
         [5.4636e-01, 8.2999e-01, 2.8467e-01, 5.3958e-02],
         [2.1611e-01, 5.0799e-01, 5.7096e-01, 7.4601e-01]],

        [[3.9213e-01, 8.7718e-02, 6.2484e-01, 2.1660e-04],
         [7.8821e-01, 5.3730e-01, 1.3683e-01, 4.0211e-01],
         [6.5483e-02, 3.4323e-01, 2.9566e-01, 5.9722e-01]]])

In [20]:
# permute
b.permute(2,0,1)

tensor([[[6.9767e-02, 5.4636e-01, 2.1611e-01],
         [3.9213e-01, 7.8821e-01, 6.5483e-02]],

        [[3.1439e-01, 8.2999e-01, 5.0799e-01],
         [8.7718e-02, 5.3730e-01, 3.4323e-01]],

        [[1.2981e-01, 2.8467e-01, 5.7096e-01],
         [6.2484e-01, 1.3683e-01, 2.9566e-01]],

        [[4.3528e-01, 5.3958e-02, 7.4601e-01],
         [2.1660e-04, 4.0211e-01, 5.9722e-01]]])

In [25]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(dim=0)

tensor([[[[0.3782, 0.7167, 0.1532],
          [0.2511, 0.9409, 0.3604],
          [0.7325, 0.1054, 0.8438],
          ...,
          [0.2950, 0.4561, 0.1979],
          [0.5324, 0.0911, 0.8269],
          [0.9054, 0.1643, 0.3184]],

         [[0.9984, 0.3737, 0.3185],
          [0.5464, 0.5409, 0.3853],
          [0.2249, 0.7732, 0.3575],
          ...,
          [0.1937, 0.7390, 0.8707],
          [0.8382, 0.7388, 0.0497],
          [0.9959, 0.0388, 0.6236]],

         [[0.4957, 0.0508, 0.4941],
          [0.7611, 0.4488, 0.4887],
          [0.9114, 0.7672, 0.6866],
          ...,
          [0.6596, 0.6673, 0.6460],
          [0.6156, 0.7798, 0.4742],
          [0.8456, 0.7972, 0.8770]],

         ...,

         [[0.3710, 0.9178, 0.3171],
          [0.0406, 0.8348, 0.2787],
          [0.9070, 0.1440, 0.6820],
          ...,
          [0.2481, 0.1060, 0.9775],
          [0.2115, 0.2154, 0.6257],
          [0.7387, 0.4521, 0.8545]],

         [[0.8621, 0.5822, 0.2940],
          [0.9629

In [26]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## NumPy and PyTorch

In [27]:
import numpy as np

In [28]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [29]:
b = a.numpy()

In [30]:
type(b)

numpy.ndarray

In [31]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [32]:
torch.from_numpy(c)

tensor([1, 2, 3])